# Generated by Django 4.1.3 on 2022-11-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chirps", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="squack",
            old_name="date_posted",
            new_name="date_squacked",
        ),
    ]
