# Generated by Django 4.1.3 on 2022-11-28 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chirps", "0002_rename_date_posted_squack_date_squacked"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Squack",
            new_name="Chirp",
        ),
    ]
