# Generated by Django 4.1.3 on 2022-11-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chirps", "0003_rename_squack_chirp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chirp",
            old_name="date_squacked",
            new_name="date_chirped",
        ),
    ]
