# Generated by Django 4.1.3 on 2022-12-03 06:49

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("chirps", "0004_rename_date_squacked_chirp_date_chirped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chirp",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=22,
                max_length=22,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
