# Generated by Django 4.1.3 on 2022-12-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chirps", "0006_alter_chirp_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="chirp",
            name="down_votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chirp",
            name="up_votes",
            field=models.IntegerField(default=0),
        ),
    ]
