# Generated by Django 4.1.3 on 2022-12-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chirps", "0008_alter_chirp_down_votes_alter_chirp_up_votes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chirp",
            name="down_votes",
        ),
        migrations.RemoveField(
            model_name="chirp",
            name="up_votes",
        ),
    ]
