# Generated by Django 4.1.3 on 2022-12-27 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chirps", "0011_remove_chirp_down_votes_remove_chirp_up_votes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chirp",
            name="down_votes",
            field=models.ManyToManyField(
                null=True, related_name="chirp_down_votes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="chirp",
            name="up_votes",
            field=models.ManyToManyField(
                null=True, related_name="chirp_up_votes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
